### ISSUE TITLE
i got an error while running some commands like song, setdp, and sticker. how to fix this?

### ISSUE THREAD

**Issue by aripstill** [BotsAppOfficial/BotsApp#129]
`[INFO] song command executed.
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at wrapper (/home/runner/botapps/node_modules/async/dist/async.js:271:20)
    at next (/home/runner/botapps/node_modules/async/dist/async.js:5793:24)
    at /home/runner/botapps/node_modules/async/dist/async.js:327:20
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/home/runner/botapps/node_modules/which/which.js:68:16)
    at E (/home/runner/botapps/node_modules/which/which.js:80:29)
    at /home/runner/botapps/node_modules/which/which.js:89:16
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/home/runner/botapps/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at wrapper (/home/runner/botapps/node_modules/async/dist/async.js:271:20)
    at next (/home/runner/botapps/node_modules/async/dist/async.js:5793:24)
    at /home/runner/botapps/node_modules/async/dist/async.js:327:20
    at wrapper (/home/runner/botapps/node_modules/async/dist/async.js:271:20)
    at next (/home/runner/botapps/node_modules/async/dist/async.js:5793:24)
    at /home/runner/botapps/node_modules/async/dist/async.js:327:20
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/capabilities.js:519:16
    at /home/runner/botapps/node_modules/fluent-ffmpeg/lib/processor.js:136:16`

**Comment by Prince-Mendiratta** [comment]
For some commands, you need to install ffmpeg on your device.
Check out the tutorial - https://youtu.be/3z9rUl9r2oA

**Comment by Samuelngala3** [comment]
> For some commands, you need to install ffmpeg on your device. Check out the tutorial - https://youtu.be/3z9rUl9r2oA

This solves the issue as for me Thank you

**Comment by Prince-Mendiratta** [comment]
I'm assuming this issue has been resolved and thus closing this.
